version: "3"

services:
  psqldb:
    restart: always
    image: postgres
    environment: 
      - POSTGRES_DB=db
      - POSTGRES_USER=bizcowork
      - POSTGRES_PASSWORD=bizcodev1!
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: 0.0.0.0, 127.0.0.1, api, backend
        DJANGO_CORS_ORIGIN_WHITELIST: 127.0.0.1:8000, google.com
    ports:
      - "8000:8000"
    depends_on: 
      - psqldb
    links:
      - psqldb
    command:
      - /backend/start-server.sh
    volumes:
      - ./backend:/backend
      - static_folder:/backend/static
    restart: always
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: /api
    volumes:
      - build_folder:/frontend/build
      - /frontend/node_modules
      - ./frontend:/frontend
    restart: always
    stdin_open: true
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - static_folder:/var/www/static
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  build_folder:
  static_folder:
