# Generated by Django 3.1.3 on 2020-12-18 06:06

import cert.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=20, unique=True, verbose_name='아이디')),
                ('email', models.EmailField(help_text='이메일이에요', max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('nickname', models.CharField(max_length=10, unique=True, verbose_name='닉네임')),
                ('profile_image', models.ImageField(default='/api/image/profile/user_default.png', upload_to=cert.models.profile_directory_path, verbose_name='프로필이미지')),
                ('mail_service', models.BooleanField(default=True, verbose_name='메일수신여부')),
                ('note_receive', models.BooleanField(default=True, verbose_name='쪽지수신여부')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('reg_time', models.DateTimeField(auto_now_add=True, verbose_name='가입시간')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저들',
                'db_table': 'cert_custom_user',
                'ordering': ['reg_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='그룹명')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='설명')),
            ],
            options={
                'verbose_name': '그룹',
                'verbose_name_plural': '그룹들',
                'db_table': 'cert_custom_group',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cert.customgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cert_custom_user_group',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ManyToManyField(through='cert.UserGroup', to='cert.CustomGroup'),
        ),
    ]
