# Generated by Django 3.1.3 on 2020-12-15 02:08

import cert.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=20, unique=True, verbose_name='user_id')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('nickname', models.CharField(max_length=10, unique=True, verbose_name='nickname')),
                ('profile_image', models.ImageField(default='/api/image/profile/user_default.png', upload_to=cert.models.profile_directory_path, verbose_name='profile_image')),
                ('mail_service', models.BooleanField(default=True, verbose_name='mail_service')),
                ('note_receive', models.BooleanField(default=True, verbose_name='note_reveive')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('reg_time', models.DateTimeField(auto_now_add=True, verbose_name='register_time')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저들',
                'db_table': 'cert_custom_user',
            },
        ),
    ]
