# Generated by Django 3.1.3 on 2020-12-15 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='group_name')),
            ],
            options={
                'verbose_name': '그룹',
                'verbose_name_plural': '그룹들',
                'db_table': 'cert_custom_group',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cert.customgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cert_custom_user_group',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ManyToManyField(through='cert.UserGroup', to='cert.CustomGroup'),
        ),
    ]
