# Generated by Django 3.1.3 on 2020-12-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0003_customgroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='description'),
        ),
    ]
