# Generated by Django 3.1.3 on 2020-12-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0005_auto_20201215_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='user',
            new_name='user_id',
        ),
    ]
