# Generated by Django 3.1.3 on 2020-12-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0006_auto_20201216_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='user_id',
            new_name='user',
        ),
    ]
