# Generated by Django 3.1.3 on 2020-12-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0007_auto_20201216_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['reg_time'], 'verbose_name': '유저', 'verbose_name_plural': '유저들'},
        ),
    ]
