# Generated by Django 3.1.3 on 2020-12-17 01:08

import cert.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0008_auto_20201216_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='그룹명'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='이메일이에요', max_length=254, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mail_service',
            field=models.BooleanField(default=True, verbose_name='메일수신여부'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=30, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(max_length=10, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='note_receive',
            field=models.BooleanField(default=True, verbose_name='쪽지수신여부'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='/api/image/profile/user_default.png', upload_to=cert.models.profile_directory_path, verbose_name='프로필이미지'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='가입일자'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='아이디'),
        ),
    ]
