# Generated by Django 3.1.3 on 2020-12-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0009_auto_20201217_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='가입시간'),
        ),
    ]
