# Generated by Django 3.1.3 on 2020-12-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(verbose_name='마지막 로그인일자'),
        ),
    ]
