# Generated by Django 3.1.3 on 2020-12-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201210_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mail_receive',
            field=models.BooleanField(default=True, verbose_name='메일수신'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='note_receive',
            field=models.BooleanField(default=True, verbose_name='쪽지수신'),
        ),
    ]
