# Generated by Django 3.1.3 on 2020-12-23 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import education.models


def forwards_func(apps, schema_editor):
    CurriculumDivision = apps.get_model("education", "CurriculumDivision")
    LectureDivision = apps.get_model("education", "LectureDivision")
    db_alias = schema_editor.connection.alias
    CurriculumDivision.objects.using(db_alias).bulk_create([
        CurriculumDivision(name=settings.DEFAULT_CURRICULUM_DIVISION),
    ])
    LectureDivision.objects.using(db_alias).bulk_create([
        LectureDivision(name=settings.DEFAULT_LECTURE_DIVISION),
    ])


def reverse_func(apps, schema_editor):
    CurriculumDivision = apps.get_model("education", "CurriculumDivision")
    LectureDivision = apps.get_model("education", "LectureDivision")
    db_alias = schema_editor.connection.alias
    CurriculumDivision.objects.using(db_alias).filter(name=settings.DEFAULT_CURRICULUM_DIVISION, description="").delete()
    LectureDivision.objects.using(db_alias).filter(name=settings.DEFAULT_LECTURE_DIVISION, description="").delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='제목')),
                ('password', models.CharField(max_length=128, verbose_name='수강비밀번호')),
                ('thumbnail', models.ImageField(default='/api/image/thumbnail/thumbnail_default.png', upload_to=education.models.thumbnail_directory_path, verbose_name='섬네일이미지')),
                ('subject', models.TextField(verbose_name='주제')),
                ('public', models.BooleanField(default=True, verbose_name='공개여부')),
                ('contents', models.TextField(verbose_name='내용')),
                ('start_date', models.DateTimeField(verbose_name='시작시간')),
                ('end_date', models.DateTimeField(verbose_name='종료시간')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '커리큘럼',
                'verbose_name_plural': '커리큘럼',
            },
        ),
        migrations.CreateModel(
            name='CurriculumDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='분류명')),
            ],
            options={
                'verbose_name': '커리큘럼분류',
                'verbose_name_plural': '커리큘럼분류',
                'db_table': 'education_curriculum_division',
            },
        ),
        migrations.CreateModel(
            name='CurriculumLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('end_date', models.DateTimeField(verbose_name='종료일')),
                ('ordering', models.IntegerField(verbose_name='순서')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.curriculum')),
            ],
            options={
                'db_table': 'education_curriculum_lecture',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='제목')),
                ('difficulty', models.CharField(choices=[('B', 'Basic'), ('D', 'Deep')], max_length=10, verbose_name='난이도')),
                ('goal', models.CharField(max_length=100, verbose_name='학습목표')),
                ('method', models.TextField(verbose_name='학습방법')),
                ('main_contents', models.CharField(max_length=100, verbose_name='주요 컨텐츠')),
                ('effect', models.CharField(max_length=100, verbose_name='기대효과')),
                ('public', models.BooleanField(default=True, verbose_name='공개여부')),
                ('contents', models.TextField(verbose_name='내용')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('curriculum', models.ManyToManyField(through='education.CurriculumLecture', to='education.Curriculum')),
            ],
            options={
                'verbose_name': '강좌',
                'verbose_name_plural': '강좌',
            },
        ),
        migrations.CreateModel(
            name='LectureDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='분류명')),
            ],
            options={
                'db_table': 'education_lecture_division',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='제목')),
                ('outline', models.CharField(max_length=100, verbose_name='개요')),
                ('url', models.CharField(max_length=258, verbose_name='영상 주소')),
                ('duration', models.IntegerField(verbose_name='강의 시간')),
                ('public', models.BooleanField(default=True, verbose_name='공개여부')),
                ('contents', models.TextField(verbose_name='내용')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_founder', to=settings.AUTH_USER_MODEL)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.lecture')),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='education.lecturedivision'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_founder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CurriculumStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(verbose_name='등록일')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.curriculum')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_curriculum_student',
            },
        ),
        migrations.CreateModel(
            name='CurriculumProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='학습 완료일')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.curriculum')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_curriculum_progress',
            },
        ),
        migrations.AddField(
            model_name='curriculumlecture',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.lecture'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='education.curriculumdivision'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_founder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='students',
            field=models.ManyToManyField(related_name='curriculum_student', through='education.CurriculumStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
