# Generated by Django 3.1.3 on 2020-12-17 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import education.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='분류명')),
            ],
            options={
                'verbose_name': '커리큘럼분류',
                'verbose_name_plural': '커리큘럼분류',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='제목')),
                ('password', models.CharField(max_length=10, verbose_name='수강비밀번호')),
                ('thumbnail', models.ImageField(default='/api/image/thumbnail/thumbnail_default.png', upload_to=education.models.thumbnail_directory_path, verbose_name='섬네일이미지')),
                ('subject', models.TextField(verbose_name='주제')),
                ('public', models.BooleanField(default=True, verbose_name='공개여부')),
                ('contents', models.TextField(verbose_name='내용')),
                ('reg_time', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.curriculumdivision')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '커리큘럼',
                'verbose_name_plural': '커리큘럼들',
            },
        ),
    ]
