# Generated by Django 3.1.3 on 2020-12-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curriculumdivision',
            table='education_curriculum_division',
        ),
    ]
