# Generated by Django 3.1.3 on 2020-12-24 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20201224_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='education.lecturedivision'),
        ),
    ]
