# Generated by Django 3.1.3 on 2020-12-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20201217_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='education.curriculumdivision'),
        ),
    ]
