# Generated by Django 3.1.3 on 2020-12-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20201217_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='classification',
            new_name='division',
        ),
    ]
