# Generated by Django 3.1.3 on 2020-12-24 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20201224_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.curriculumdivision'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.lecturedivision'),
        ),
    ]
