# Generated by Django 3.1.3 on 2020-12-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20201224_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='순서'),
            preserve_default=False,
        ),
    ]
