# Generated by Django 3.1.3 on 2020-12-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_lesson_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='수강비밀번호'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='subject',
            field=models.TextField(blank=True, verbose_name='주제'),
        ),
    ]
